require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, "16.6"
prepare_react_native_project!

target 'BridtvSdkModuleExample' do
  config = use_native_modules!

  ENV['RCT_NEW_ARCH_ENABLED'] = '0'

  use_frameworks! :linkage => :static

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BridtvSdkModuleExampleTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
  end
end
